import Header from "@/components/Header";
import HeaderUpSection from "@/components/HeaderUpSection";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="px-3 sticky top-0 bg-white">
          {/* Header */}
          <HeaderUpSection />
          <Header />
        </div>
        <div className="flex  sm:max-w-xl md:max-w-3xl lg:max-w-4xl xl:max-w-7xl mx-auto">
          <div className="hidden lg:flex  border-r h-screen w-60">
            {/* sidebar */}
            <Sidebar />
          </div>
          <div className="w-full">{children}</div>

          <div>{/* suggestion */}</div>
        </div>
      </body>
    </html>
  );
}
