import Header from "@/components/Header";
import HeaderUpSection from "@/components/HeaderUpSection";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="px-3">
          {/* Header */}
          <HeaderUpSection />
          <Header />
        </div>
        <div>
          <div>{/* sidebar */}</div>
          <div>
            {/* mainpage */}
            {children}
          </div>
          <div>{/* suggestion */}</div>
        </div>
      </body>
    </html>
  );
}
